### ISSUE TITLE
I got an issue when I tested the example data

### ISSUE THREAD

**Issue by nakkulla** [GuanLab/FastClone_GuanLab#1]
Hi there,
Thank you for developing this wonderful tool.
However, when I tested this tool for the example data(/FastClone_GuanLab/t1.tsv), 

-----------------------------------------------------------------------------------------------------
/fastclone/subclone.py:265: RuntimeWarning: invalid value encountered in subtract
  scores = numpy.exp(l - l_sample[:, None])
[2020-09-13 15:47:54.077797] WARNING: fastclone.subclone: Maximum iteration reached but the EM did not converged.
/fastclone/subclone.py:276: RuntimeWarning: invalid value encountered in subtract
  scores = pandas.DataFrame(numpy.exp(l - l_sample[:, None]),
[2020-09-13 15:48:00.155912] WARNING: fastclone.subclone: Maximum iteration reached but the EM did not converged.
------------------------------------------------------------------------------------------------------

this warning is occurred and couldn't find any clone. This warning is also occurred in my data and couldn't find clone as well.
However, for example, "/FastClone_GuanLab/colon_data/cp18_t1.tsv" data doesn't have this warning and work well.
I just wonder whether this warning means something wrong or not.

Could you help me to solve this problem?

Best Regards, Andy.

**Comment by Yaoyx** [comment]
Hi Andy, thanks a lot for your feedback. The runtime warning is due to a very small "probability value" which would result in -inf when logpmf is applied to calculate l. This is caused by small var_counts or variant_freq. FastClone should be fine, if there are only a few genes have this problem. And the second warning is set up by FastClone itself. If the EM does not converge after a certain amount of iterations, FastClone will end there and prompt users.

Do you have an example of your data? So I probably can check the problem further.

**Comment by nakkulla** [comment]
Thank you for kind reply! 
My problem may be caused by the reason which you described; small var_counts.
Actually, my data is WGS data which depth is around 30X. Additionally, I did some filtering of somatic mutation for my data and after that, it only has few mutations.
If you don't mind, could you check the example of my data? if you need more details, just let me know. :)

[exampledata.zip](https://github.com/GuanLab/FastClone_GuanLab/files/5231157/exampledata.zip)

Thank you so much again!

Andy.
